apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: fmt-lbl
    name: fmt-lbl

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
     name: fmt-lbl
     namespace: fmtest
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - namespaces
    - services
    - deployments
    - jobs" 
    verbs:
    - get
    - list
    - watch

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: fmt-lbl
  subjects:
  - kind: ServiceAccount
    name: fmt-lbl
    namespace: fmtest
  roleRef:
    kind: ClusterRole
    name: fmt-lbl
    apiGroup: rbac.authorization.k8s.io

- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      app: fmt-lbl
    name: fmt-lbl
  spec:
    selector:
      matchLabels:
        logging: fmt-lbl
    template:
      metadata:
        labels:
          logging: fmt-lbl
        name: fmt-lbl
      spec:
        containers:
        - name: fluentd
          env:
          - name: K8S_HOST_URL
            value: https://kubernetes.default.svc.cluster.local
          - name: USE_JOURNAL
            value: "false"
          - name: MONGODB_HOSTNAME
            value: fmt-mongodb
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_DATABASE
            value: fmt
          - name: MONGODB_COLLECTION
            value: fmt_cl
          - name: MONGODB_USERNAME
            value: user
          - name: MONGODB_PASSWORD
            value: fmt1234
          image: caruccio/logging-fluentd:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: config-volume
            mountPath: /etc/fluent/config.d        
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        priorityClassName: system-node-critical
        serviceAccount: fmt-lbl
        serviceAccountName: fmt-lbl
        terminationGracePeriodSeconds: 30
        #restartPolicy: Always
        dnsPolicy: ClusterFirst
        volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config-volume
          configMap:
            name: fmt-fluentd-config-v0.1
          
kind: List
metadata: {}            
